services:
  asr-api-cpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: asr-transcribe-cpu
    ports:
      - "8076:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./temp:/app/temp
      - ./logs:/app/logs
    environment:
      - TEMP_PATH=/app/temp
      - LOG_LEVEL=INFO
      - HF_HOME=/root/.cache/huggingface
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    restart: unless-stopped
