version: '3.8'

services:
  asr-api-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: asr-transcribe-gpu
    ports:
      - "8075:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./temp:/app/temp
      - ./logs:/app/logs
    environment:
      - TEMP_PATH=/app/temp
      - LOG_LEVEL=INFO
      - HF_HOME=/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
