version: '3.8'

services:
  asr-api-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: asr-transcribe-cpu
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./temp:/app/temp
      - ./logs:/app/logs
    environment:
      - TEMP_PATH=/app/temp
      - LOG_LEVEL=INFO
      - HF_HOME=/root/.cache/huggingface
    restart: unless-stopped
